name: jaspr_markdown_example
description: A new jaspr project.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  jaspr: ^0.19.0
  jaspr_markdown:
    path: ../

dev_dependencies:
  build_runner: ^2.4.14
  build_web_compilers: ^4.1.0
  jaspr_builder: ^0.19.0
  lints: ^5.1.1

jaspr:
  mode: static
